### ISSUE TITLE
plugs.js的问题

### ISSUE THREAD

**Issue by kasiait521** [zoujingli/Think.Admin#1]
在plugs.js中，我看到这个写法：reinit.call(this), setTimeout(reinit, 500), setTimeout(reinit, 1000);请问一下，用逗号是什么意思？还有这个地方为什么要500毫秒和1000毫秒都执行呢

**Comment by zoujingli** [comment]
动态html代码插入dom后不一定立即生效，需要延时初始化事件，目前这里尝试了多次处理。
