### ISSUE TITLE
有两个疑问想请教下

### ISSUE THREAD

**Issue by shenfeng07** [zoujingli/Think.Admin#19]
有两个疑问想请教下
1.为什么不使用模型？
2.为什么要把入口文件放在根目录？

**Comment by zoujingli** [comment]
1、系统减少对ThinkPHP依赖，方便后面跨版本的升级；关于模型的使用完全可以自行封装，合适就好，不一定要使用到，目前系统中已经有一套完整的CURD机制，ThinkPHp内置的Model没必要使用到
2、入口文件放到根目录下，完全是考虑到部署问题，很多情况下是不方便指定目录的，尤其是批量部署及vhost环境，因此入口文件统一放置于根目录下，其实对于安全来说也没什么影响，对于直接访问PHP类文件是没有结果的，毕竟PHP类是不会自改运行，即使把目录暴露在外面，也没多大关系
