### ISSUE TITLE
报错：网站上传图片模块不存在，index.php

### ISSUE THREAD

**Issue by nextoneme** [zoujingli/Think.Admin#20]
上传图片处点开均会提示index.php不存在，网站icon编辑及微信图文编辑处，如图

![wx20170616-231029](https://user-images.githubusercontent.com/9179487/27233089-e75ec532-52ea-11e7-9aa9-165a195636e3.png)

**Comment by nextoneme** [comment]
根据报错提示去掉index.php让其直接访问剩余路径才会没问题

**Comment by zoujingli** [comment]
webroot 带路径的时候，URL上需要带上index.php

**Comment by zoujingli** [comment]
框架默认入口是index.php，JS会拼接index.php

**Comment by zoujingli** [comment]
Host配置请参考项目说明文件
