### ISSUE TITLE
微信支付配置 在本地储存不为path时报错

### ISSUE THREAD

**Issue by hsmustard** [zoujingli/Think.Admin#226]
作者您好，我在测试项目时发现，在后台配置 微信支付配置 的时候，如果在系统配置--配置本地服务器存储--访问协议 不为path时 会出现代码报错
![peizhi2](https://user-images.githubusercontent.com/40329444/74320711-15041180-4dbc-11ea-852d-4c49f71588bd.png)

![error](https://user-images.githubusercontent.com/40329444/74320703-0e759a00-4dbc-11ea-8454-a6c9645c2938.png)

--
我根据错误提示修改代码后发现不会报错，请问是我的环境问题还是我的配置不正确呢？
![f](https://user-images.githubusercontent.com/40329444/74320756-29480e80-4dbc-11ea-8e41-154908c4f266.png)

---
环境：php 7.3.4
mysql 8.0.12

**Comment by zoujingli** [comment]
证书上传使用 safe 模式，不会走这些流程 v6
