### ISSUE TITLE
列表的列太多会超出

### ISSUE THREAD

**Issue by jiangxiulong** [zoujingli/Think.Admin#228]
![image](https://user-images.githubusercontent.com/18181655/77220980-761fc180-6b80-11ea-825f-33d1115b95c1.png)

**Comment by jiangxiulong** [comment]
![image](https://user-images.githubusercontent.com/18181655/77220989-8afc5500-6b80-11ea-9452-a1f08c204cb8.png)

**Comment by jiangxiulong** [comment]
列表多了会超出table   我发的照片能看到吗 好像看不到照片哦

**Comment by zoujingli** [comment]
有发现此问题，还没有找到解决方案。。。

**Comment by dtapps** [comment]
> 列表多了会超出table 我发的照片能看到吗 好像看不到照片哦

有一个常见的做法只是不完美！就是加滚动条

![image](https://user-images.githubusercontent.com/16093106/78466447-c75cb300-7733-11ea-8c90-df1bdc221c80.png)

**Comment by yushengling** [comment]
这个表格超出,怎么调节滚动条方案

**Comment by zoujingli** [comment]
有考虑过，不过效果不怎么样。
现在有考虑两种
一、right 部分根据 table width 自动调整
二、内容 table 使用 layui table 实现，自动处理表格
在测试调整中，后面调整好了，可以使用  php think xadmin:install 来更新

**Comment by zoujingli** [comment]
已经处理
