### ISSUE TITLE
Service 模块是不是不发布了?

### ISSUE THREAD

**Issue by lesamly** [zoujingli/Think.Admin#231]
Service 模块是不是不发布了?
现在的微信开发平台似乎都是请求你们的链接，现在没有代码部署，你提供的 service 库也是 v5 版本的，有没有 v6 版本的呢？

**Comment by zoujingli** [comment]
代码可以邮件发给你，留个邮箱就行

**Comment by zoujingli** [comment]
[service_v6.zip](https://github.com/zoujingli/ThinkAdmin/files/4584711/service_v6.zip)
ThinkAdmin v6 的 Service 模块，后面不准备开源，这里收藏下！

**Comment by lesamly** [comment]
> [service_v6.zip](https://github.com/zoujingli/ThinkAdmin/files/4584711/service_v6.zip)
> ThinkAdmin v6 的 Service 模块，后面不准备开源，这里收藏下！

谢谢

**Comment by yzphp** [comment]
用了这个v6的service 但是一直提示 component ticket is invalid hint 请问是什么原因呢  非常感谢！

**Comment by zoujingli** [comment]
没有收到开放平台推送过来的 ticket
