### ISSUE TITLE
任务错误

### ISSUE THREAD

**Issue by yzphp** [zoujingli/Think.Admin#233]
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /www/wwwroot/demo.iwangr.cn/vendor/topthink/think-helper/src/helper.php on line 26

**Comment by yzphp** [comment]
请问怎么处理呢

**Comment by zoujingli** [comment]
建议检查下 command 的php运行版本，可以使用 php -v 查看 php 版本
