### ISSUE TITLE
使用composer update更新后，后台访问的目录全部缺少应用模块名称

### ISSUE THREAD

**Issue by cfs168** [zoujingli/Think.Admin#245]
`<a data-target-tips="系统参数配置" data-open="/config/index.html" data-menu-node="m-2-4-11"><span class="nav-icon padding-left-5 layui-icon layui-icon-set"></span><span class="nav-text padding-left-5">系统参数配置</span></a>`
1. 上面系统管理菜单链接中的data-open全部都少了/admin，其他的像微信模块则少了/wechat；
2. 前台index模块少了/index，这个是默认模块，少了没问题，可以正常访问

**Comment by zoujingli** [comment]
现在 composer update 之后是否正常

**Comment by cfs168** [comment]
更新后可以了，谢谢！

**Comment by zoujingli** [comment]
ok，可能是之后更新tp官方的多应用组件所致！已经回滚相关代码

**Comment by cfs168** [comment]
已解决，是本地composer.json文件没有同步更新到线上导致的，可以看到线上已移除了topthink/think-multi-app，复制线上最新的composer.json再composer update即可
