### ISSUE TITLE
关于V6能直接访问admin.api文件的问题

### ISSUE THREAD

**Issue by xuwenfeng93** [zoujingli/Think.Admin#247]
![QQ截图20201022183645](https://user-images.githubusercontent.com/48546665/96861158-4a5a1680-1496-11eb-87d8-3cff710f07c5.png)
这个文件能直接访问是正常的吗？

**Comment by zoujingli** [comment]
图片看不到。。。

**Comment by zoujingli** [comment]
app/admin/api/Update.php
这个文件可以直接删除，不影响使用。
新版本已经增加自动删除机制
