### ISSUE TITLE
能否直接更新thinkPHP核心文件

### ISSUE THREAD

**Issue by xuwenfeng93** [zoujingli/Think.Admin#248]
如题，能否直接更新thinkPHP核心文件，因为vendor 自己在安装了很多别的插件，如果composer update --profile --prefer-dist --no-dev --optimize-autoloader更新会把vendor删除在更新

**Comment by zoujingli** [comment]
可以指定组件更新

**Comment by zoujingli** [comment]
阅读文档
https://thinkadmin.top/system-upgrade
