### ISSUE TITLE
配置nginx+phpfpm 访问首页死循环

### ISSUE THREAD

**Issue by lvxj** [zoujingli/Think.Admin#249]
nginx配置

server {
  listen 80;
  server_name walle.dev.com;
  access_log /Users/seven/Developer/logs/php/walle_dev_nginx.log combined;
  error_log  /Users/seven/Developer/logs/php/walle_dev_nginx_error_nginx.log;

  index index.html index.htm index.php;
  root  /Users/seven/Developer/phpenv/walleManager/public;

  #error_page 404 = /404.html;
  #error_page 502 = /502.html;

  if (!-e $request_filename) {
  rewrite ^(.*)$ /index.php$1 last;
}

   location / {
      try_files $uri $uri/ /index.php$is_args$args;
    }

  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/tmp/php-cgi.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
    expires 30d;
    access_log off;
  }
  location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
  }
  location ~ /\.ht {
    deny all;
  }
}

**Comment by zoujingli** [comment]
估计是session问题

**Comment by zoujingli** [comment]
环境配置问题
