### ISSUE TITLE
本地调试未登录状态 输入模块链接会直接打开看到

### ISSUE THREAD

**Issue by lpf1117** [zoujingli/Think.Admin#251]
本地调试未登录状态 输入模块链接会直接打开看到

**Comment by lpf1117** [comment]
例如：http://pingtai.com/admin.html#/admin/user/index.html admin退出登录在浏览器输入链接：http://pingtai.com/admin/user/index.html 可以直接显示

**Comment by zoujingli** [comment]
测试正常，会不会是浏览器缓存？
原理：退出时会清理掉SESSION数据，访问 user 是返回登录信息。
