### ISSUE TITLE
上传附件到本地是否可以增加自动压缩图片，处理图片大小的功能

### ISSUE THREAD

**Issue by freechen** [zoujingli/Think.Admin#254]
如降低图片大小，减少图片尺寸等

**Comment by cfs168** [comment]
最好可以在链接上加长宽的参数生成到临时文件夹，下次可以直接用生成的图片打开
两种文案：
原图：https://domain/abc.jpg
第一种：https://domain/abc.jpg?w=400&h=300 接收到图片参数创建或输出对应尺寸的图片
第二种：https://domain/abc_400_300.jpg 找不到时以伪静态的方式创建缩略图

**Comment by zoujingli** [comment]
建议用云存储处理，也就是在链接上加参数。用php处理不安全，而且耗资源
