### ISSUE TITLE
升级后当前模板名都没有了，看下是什么原因，谢谢！

### ISSUE THREAD

**Issue by cfs168** [zoujingli/Think.Admin#256]
后台 的当前访问是admin#/index.php/work/data_transfer/index.html?spm=m-67-91-92
然后编辑按钮{:url("edit")}生成的链接是/index.php/data_transfer/edit.html?id=21
按理来说生成的链接应该是/index.php/word/data_transfer/edit.html?id=21，少了word，在微信模板中也是一样的
文件全部都更新了的，麻烦看下是什么情况，谢谢！

**Comment by zoujingli** [comment]
library 什么版本？

**Comment by zoujingli** [comment]
新版本是基于 ThinkLibrary 自带的多应用组件，不再使用 tp 官方的组件。
URL 生成可能就是因为这个原因，尝试更新下再试试

**Comment by cfs168** [comment]
核心框架ThinkPHP Version 6.0.5
管理程序ThinkAdmin Version 6.0.22

已经更新到最新版本，还是没有生成完整的链接，现在只有系统管理这个模板生成的url能正常访问，其他的模块生成的url缺少当前模板名，菜单生成的链接没问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zoujingli/ThinkAdmin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午2:34
收件人:&nbsp;"zoujingli/ThinkAdmin"<ThinkAdmin@noreply.github.com&gt;;
抄送:&nbsp;"Victory"<766118811@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zoujingli/ThinkAdmin] 升级后当前模板名都没有了，看下是什么原因，谢谢！ (#256)





 
library 什么版本？
