### ISSUE TITLE
v5:求阿里云oss上传文档

### ISSUE THREAD

**Issue by muxik** [zoujingli/Think.Admin#259]
我在开发的时候遇到了, 需要上传视频文件到阿里云oss储存但是没有看到文档里有相关的内容，Version: thinkadmin v5

**Comment by zoujingli** [comment]
配置即可，都是驱动模式

**Comment by muxik** [comment]
> 配置即可，都是驱动模式

已经用自带的阿里云OSS SDK解决了，不过还是谢谢
