### ISSUE TITLE
视图中的字段值获取问题

### ISSUE THREAD

**Issue by yuzhou03** [zoujingli/Think.Admin#26]
请教下：
比如数据库表中的设备操作系统os的值为数字，含义如下1 iOS 2Android 3 WP
在页面展示时，不想展示数字，而是他对应的含义。
在model总可以设置模型获取器。但是在表单中如何用到getOsAttr的返回值呢？
$vo.os达不到效果。

@zoujingli

**Comment by yuzhou03** [comment]
可以在html中加一堆if判断来是实现。但是页面中不该有这么多的判断逻辑，放在model层，逻辑会清晰一些。

**Comment by zoujingli** [comment]
目前不考虑使用模型，简单就好了

**Comment by yuzhou03** [comment]
谢谢回复
