### ISSUE TITLE
微信公众平台直接模式，通过网页授权获取粉丝信息，解析 GET 参数失败问题

### ISSUE THREAD

**Issue by smallpurebywu** [zoujingli/Think.Admin#263]
### 方法路径 app\wechat\service\WechatService -> getWebOauthInfo()

_此处，若$source存在锚点#号，如 https://xxx.com/#/home?a=1&b=2 ，parse_url返回null，参数丢失导致微信授权回调地址异常_
**parse_str(parse_url($source, PHP_URL_QUERY), $params);**

_这里的 $params 自然就缺失 a=1&b=2 参数_
**$location = strstr("{$source}?", '?', true) . '?' . http_build_query($params);**

**Comment by zoujingli** [comment]
具体需要实践测试，目前我自己使用未再发现此问题。
