### ISSUE TITLE
uris方法找不到

### ISSUE THREAD

**Issue by nibamao** [zoujingli/Think.Admin#268]
composer install后uris方法找不到

**Comment by leewei233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信收到

**Comment by NEETLee** [comment]
把git回滚到[e613af88535646d4dac33dc6ec2d22c98908937a](https://github.com/zoujingli/ThinkAdmin/commit/e613af88535646d4dac33dc6ec2d22c98908937a)
重新安装就可以了
应该是[ddd01c6f46e753e29e0fee255164872556bce152](https://github.com/zoujingli/ThinkAdmin/commit/ddd01c6f46e753e29e0fee255164872556bce152)
造成的
