### ISSUE TITLE
admin-auth-inde-数据回调处理，里面的sql加上where会返回错误

### ISSUE THREAD

**Issue by 18190684376** [zoujingli/Think.Admin#271]
返回错误：
Fatal error: Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in
![Snipaste_2023-01-13_11-51-00](https://user-images.githubusercontent.com/34847240/212233460-3613202c-2f26-44cb-bc31-6faa69c254bc.png)

**Comment by leewei233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信收到

**Comment by StrKang** [comment]
你where方法倒是写参数啊，不写的话就把where删了

**Comment by zoujingli** [comment]
建议阅读下 Tp 官方手册，详细了解下 ORM 使用。

https://doc.thinkphp.cn
