### ISSUE TITLE
本地自己配置了个站点,login成功就是这个?

### ISSUE THREAD

**Issue by adiudiuu** [zoujingli/Think.Admin#273]
![image](https://user-images.githubusercontent.com/31238774/217741415-000cd84e-5a0f-4000-9486-b90312740b87.png)

**Comment by zjkal** [comment]
看着像是忘了进行composer install操作

**Comment by leewei233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信收到

**Comment by zoujingli** [comment]
使用正常点的域名，同时 composer update 更新组件。
