### ISSUE TITLE
后台页面有没有考虑：使用iframe或者tab打开？

### ISSUE THREAD

**Issue by wzhih** [zoujingli/Think.Admin#274]
感觉后台使用中，经常会打开不同页面，这样子可能就需要打开不同标签才能解决

**Comment by zoujingli** [comment]
抱歉，后台是类似单页程序实现，不支持 tab 方式，也不会考虑使用 iframe 方式。

**Comment by leewei233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信收到
