### ISSUE TITLE
how access admin page while delete link login?

### ISSUE THREAD

**Issue by tieumap** [zoujingli/Think.Admin#279]
dear you guys!
i found some site use thinkadmin
first time they have link to login admin page
https://zcccev.com/admin/login/index_2.html
after they know i got user, password, they delete link login i cannot access
but i has been insert beef framework and know they still access admin page
![image](https://github.com/zoujingli/ThinkAdmin/assets/140687353/88f5cba0-bddd-4672-a429-16f5ddb35d24)

i want ask, how they can do that? they has been delete link login, but they still access admin page to manager
p/s: that site use thinkadmin to make website scam, then i want hack them

**Comment by tieumap** [comment]
can anyone help me?

**Comment by tieumap** [comment]
pls help me

**Comment by bapcai02** [comment]
@tieumap It is possible that the system has blocked all IPs, only allowing IPs that they allow to access the system

**Comment by tieumap** [comment]
dear bapcai02
other site i still access normal mate :D (other site same ip)

**Comment by tieumap** [comment]
hi big guys!
i guess they block all IPS, only allowing IPs that they allow to access the system
so can i use beef proxy to access that link?

**Comment by bapcai02** [comment]
> dear bapcai02 other site i still access normal mate :D (other site same ip)

So what, they can block all ips, only allowing a few ips to access
