### ISSUE TITLE
微信相关组件怎么快速去掉呢？

### ISSUE THREAD

**Issue by BarryShieh** [zoujingli/Think.Admin#28]
因为我这个项目的后台和微信无关，虽然可以隐藏菜单，但是微信关联的一堆代码文件还是在的，作为强迫症很难接受。By the way，这个后台很简洁，很好看，作者加油！

**Comment by yuzhou03** [comment]
删除掉wechat目录不行吗？

**Comment by yuzhou03** [comment]
试了下，隐藏微信管理菜单，可以在导航栏生效。

**Comment by zoujingli** [comment]
删除对应代码，删除菜单就可以了
