### ISSUE TITLE
chrome下后台登录无法选择修改密码/修改资料/退出登录

### ISSUE THREAD

**Issue by gitzwt** [zoujingli/Think.Admin#34]
不知道是不是最近chrome核心更新导致不兼容,前段时间这后台右上角的功能还能点;检查后发现
.console-topbar .dropdown .dropdown-menu{z-index:1;....   这z-index:1这让a标签在按钮样式下了,改大ok

**Comment by yuzhou03** [comment]
我也发现此问题，还以为是代码的bug...

**Comment by gitzwt** [comment]
win7下浏览器打开可以,win10和iOS10下不行
