### ISSUE TITLE
使用 layui 默认的 上传组件时, 如果组件在 from 里 并 属性为 data-auto="true" ,上传组件上传后 会触发 from 提交

### ISSUE THREAD

**Issue by ming200825** [zoujingli/Think.Admin#37]
使用 layui 默认的 上传组件时, 如果组件在 from 里 并 属性为 data-auto="true" ,上传组件上传后 会触发 from 提交 动作 ,但是想传图后 或获取图片地址并不想提交from 

<form class="layui-form layui-box" style='padding:10px 10px 10px 0' action="__SELF__" data-auto="true" method="post">

 <input name="file" lay-title="上传图片" class="layui-upload-file" type="file">
  <input name="url_m" title="file_m" type="hidden">
</form>

**Comment by ming200825** [comment]
`<form class="layui-form layui-box" style='padding:10px 10px 10px 0' action="__SELF__" data-auto="true" method="post">
 <input name="file" lay-title="上传图片" class="layui-upload-file" type="file">
            <input name="url_m2" title="file_m2" type="hidden">
</form>

`

**Comment by zoujingli** [comment]
可能是你的表单元素用的不当，如果是 button，需要把 type 声明为 button，不能为默认的

**Comment by ming200825** [comment]
http://www.layui.com/v1/demo/upload.html   是这个组件 另一个  from 里 并属性为 data-auto="true" 就会 触发 from 提交 动作

**Comment by zoujingli** [comment]
layui自带的上传文件模块，会生成一个form用来上传文件，在相当于在form中套一个form，这才导致外层form被提交，建议使用 data-file 去提交文件
