### ISSUE TITLE
关于自动创建 

### ISSUE THREAD

**Issue by tangbingbing** [zoujingli/Think.Admin#40]
请问一下你这个框架在 自动创建编辑页面时 编辑页面的form里面 action怎么创建的是全路径呢 请问这个可以修改成创建相对路径不. 还有就是这 编辑的 form 是怎么生成的呢

**Comment by zoujingli** [comment]
可以，form表单默认使用的是__SELF__ , 当然你也可以用相对路径，不过要保证能够正常POST访问你的方法
