### ISSUE TITLE
Admin ajax加载失败，界面一直转圈

### ISSUE THREAD

**Issue by Jamling** [zoujingli/Think.Admin#41]
如遇服务端错误（HTTP 500），后台Ajax操作，此时，界面冻结，无法操作，除非手动点击浏览器的刷新按钮重新加载界面。
此issue对于debug阶段影响很大。非常不方便。

**Comment by zoujingli** [comment]
问题在调试中，稍候给予回复...

**Comment by zoujingli** [comment]
代理已经提交，请更新 admin/plugs.js 文件
