### ISSUE TITLE
反馈样式问题

### ISSUE THREAD

**Issue by LaoHuCai** [zoujingli/Think.Admin#43]
\static\theme\default\css\console.css文件

.console-topbar .dropdown .dropdown-menu {
    z-index: 1;
    font-size: 12px;
    border-radius: 0;
    -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1)
}

z-index: 1 会导致下拉菜单无法点击

**Comment by zoujingli** [comment]
可以提供下问题出现浏览器版本信息吗？在当前环境下，可以调整出来吗？

**Comment by LaoHuCai** [comment]
用的是chrome，把z-index注释掉就没有问题了

**Comment by LaoHuCai** [comment]
在您的样式网站也测试了，还是那样的问题，被<div class="dropdown-backdrop"></div>遮挡住了
