### ISSUE TITLE
FileService::getBaseUriLocal() 返回的路径不对

### ISSUE THREAD

**Issue by Jamling** [zoujingli/Think.Admin#47]
缺少了 Think.Admin  （${root}）
```
        dump($this->request->root(true));
        dump(FileService::getBaseUriLocal());

```

结果为

```
string(33) "http://192.168.133.15/Think.Admin"
string(36) "http://192.168.133.15/static/upload/"

```

**Comment by zoujingli** [comment]
`    /**
     * 获取服务器URL前缀
     * @return string
     */
    public static function getBaseUriLocal()
    {
        $request = request();
        $base = $request->root();
        $root = strpos($base, '.') ? ltrim(dirname($base), DS) : $base;
        if ('' != $root) {
            $root = '/' . ltrim($root, '/');
        }
        return ($request->isSsl() ? 'https' : 'http') . '://' . $request->host() . "{$root}/static/upload/";
    }`
我当前环境测试是正常的

**Comment by Jamling** [comment]
如果部署的文件夹带. 如Think.Admin。将会执行ltrim(dirname($base), DS)。导致root为空。然后就少了Think.Admin这一级。

**Comment by zoujingli** [comment]
```php
    /**
     * 获取服务器URL前缀
     * @return string
     */
    public static function getBaseUriLocal()
    {
        $appRoot = request()->root(true);
        $uriRoot = preg_match('/\.php$/', $appRoot) ? dirname($appRoot) : $appRoot;
        return "{$uriRoot}/static/upload/";
    }
```
你看这样，可以解决你的问题不？

**Comment by zoujingli** [comment]
相关代码已经更新！

**Comment by Jamling** [comment]
可以的，我自己修改的代码是使用 TP的`request->root(true)`来生成的。不过，上传那部分调用了FileService。偶然发现的。
