### ISSUE TITLE
分页查询bug

### ISSUE THREAD

**Issue by lgb531** [zoujingli/Think.Admin#48]
当选择到page>1的其他页面去执行搜索条件 由于链接里面page>1会导致查询无结果
解决办法：

`<input type="hidden" name="page" value="1">`

把这个加到搜索条件前 表示执行搜索时候page=1

**Comment by zoujingli** [comment]
已收录，下个版本修复

**Comment by zoujingli** [comment]
问题已经解决，form-search 时，page参数会自动清除掉，永远保持第一页数据显示！

**Comment by qindj** [comment]
这个问题在新版还是存在，感觉是layui接管了form提交，我设了断点，但是不会运行到admin.js里body on submit方法

**Comment by zoujingli** [comment]
demo.thinkadmin.top 测试下，目前没有发现此问题
