### ISSUE TITLE
未登陆时，能看到系统导航，但是点击导航提示没有权限访问。

### ISSUE THREAD

**Issue by 512765140** [zoujingli/Think.Admin#50]
当开发了多个模块后，系统菜单展示有BUG。
未登陆时，能看到系统所有导航，但是点击导航提示没有权限访问。
抱歉，您还有登陆获取访问权限。
设置了普通管理员，不授权的节点导航，一样展示出来，但也提示没有权限访问。
系统功能一切正常，没有报错，没有错误日志。

**Comment by 512765140** [comment]
在调用_filterMenu前，dump出菜单，和节点的数据，也发现没有问题，无论是结构，还是url。。感觉是_filterMenu这个方法不够完善

**Comment by 512765140** [comment]
控制器方法名字不能带有下划线，例如我控制器中一个方法是 hello_test，节点和菜单对应的也是hello_test，这样就会出现不登陆也能看到所有导航，当我删掉下划线，改为hellotest，菜单显示就正常了。

**Comment by limho0202** [comment]
_filterMenu 在这个方法里 $node = join('/', array_slice(explode('/', preg_replace('/[\W^_]/', '/', $menu['url'])), 0, 3)); 之后加一个 $node = trim($node,'/'); 就解决了

**Comment by zoujingli** [comment]
代码已经修正，麻烦有空更新下代码！
