### ISSUE TITLE
系统用户授权有bug

### ISSUE THREAD

**Issue by npwayne** [zoujingli/Think.Admin#54]
用户授权修改无效

**Comment by zoujingli** [comment]
请说明下具体原因

**Comment by npwayne** [comment]
后台系统用户->授权->修改访问授权后依然勾选

**Comment by npwayne** [comment]
用户编辑的访问授权选项样式失效

**Comment by zoujingli** [comment]
代码更新下，试试看盾

**Comment by npwayne** [comment]
修改授权以后提示成功，但是依然默认全部勾选

**Comment by zoujingli** [comment]
我这里测试是ok的，有修改过代码吗？

**Comment by npwayne** [comment]
没有修改过，我用你提供的测试服务器也有这个问题。  http://think.ctolog.com测试后台中所有用户都是勾选着用户管理和商品管理两个权限的，你看看是不是全部默认勾选了

**Comment by zoujingli** [comment]
没有商品管理吧？

**Comment by zoujingli** [comment]
其它的测试都是正常的啊

**Comment by npwayne** [comment]
![image](https://user-images.githubusercontent.com/30310451/31535345-62c9efae-b02d-11e7-8c42-bf21f20a4be0.png)

**Comment by zoujingli** [comment]
修改上模板文件，原来是checked属性多写了

**Comment by npwayne** [comment]
嗯 谢谢，这个后台后文档吗

**Comment by zoujingli** [comment]
暂时还没有写完，其实这个框架平台是最简单的模式，只要自已看看就知道了，大多都是通用性质编程思路，没有用过多的封装

**Comment by npwayne** [comment]
好的 谢谢 我还是个新手，想多看看学习一下，有些东西看着还是会有点吃力
