### ISSUE TITLE
这种url地址能不能变更一下？

### ISSUE THREAD

**Issue by nottellyou** [zoujingli/Think.Admin#61]
http://local.xxxxx.com/admin#/demo/plugs/region?spm=m-87-90

为什么要加一个#号呢？？直接：
http://local.xxxxx.com/admin/demo/plugs/region?spm=m-87-90

这样不更好些嘛。还是说可以修改配置文件换成下面这个url地址？？

**Comment by zoujingli** [comment]
不能改的，后台的结构是局部加载...

**Comment by haidongZhang** [comment]
这个#号对seo很不友好。

**Comment by zoujingli** [comment]
后台不需要seo吧
